version: "3"
services:
  web:
    # replace username/repo:tag with your name and image details
    image: josecolella/flask-nginx-businessunits-vis:1.0
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: "0.5"
          memory: 150M
      restart_policy:
        condition: on-failure
    ports:
      - "80:80"
    networks:
      - webnet
  cache:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - webnet
networks:
  webnet:
